### PR TITLE
Merge changes from main branch

### PR DESCRIPTION
**Pull request by nathanwhit**
#7 was accidentally targeting the main branch, so this PR pulls the changes into `dev`

### CODE REVIEW

**Review by atodorov — APPROVED** [review]
LGTM but you've got failures with the Rust nightly compiler. Preferably we fix them before merging.

**Comment by nathanwhit** [comment]
Opened #14 to fix the nightly compiler jobs.

**Comment by CAGS295** [comment]
@nathanwhit

**Comment by atodorov** [comment]
@nathanwhit from what I can tell this PR needs a rebase so we can see the CI jobs pass and can be merged.

**Comment by nathanwhit** [comment]
@atodorov Looks like I can't rebase because of write privileges (it would modify `main` in the process). I think I'll have to open a new PR.

**Comment by nathanwhit** [comment]
Replaced by #20.

**Pull request closed without merging**
