### PR TITLE
CRB-263 Reverse award

### PR DESCRIPTION
**Pull request by CAGS295**
## Description Of Changes
Award miners in ascending order

## Code Review Checklist

- [x] Target branch is `dev`, unless we're merging from `dev` to `main`
- [x] All CI checks reports PASS

### CODE REVIEW

**Review by atodorov — COMMENTED** [review]
The reward function and in particular the last line which has changed appears to be covered by existing tests but I don't see any test related changes. If you change the behavior I am expecting existing tests to fail. Given that they don't this means either testing is poor or it is missing some assertions. 

@CAGS295 I see `housekeeping_reward_fork`, `housekeeping_reward_in_chain` and `housekeeping_within_block_reward_count` which sound related. Can you point me in the right direction? Which function is supposed to be the test for this functionality ?

**Review by atodorov — APPROVED** [review]
My previous question has been answered on Slack.

**Review by nathanwhit — APPROVED** [review]
Looks good to me

**Review by atodorov — CHANGES_REQUESTED** [review]
@CAGS295 needs rebase + conflict resolution

**Review by atodorov — CHANGES_REQUESTED** [review]
Needs rebase + conflict resolution.

**Review by atodorov — APPROVED** [review]
- CI reports PASS
- functional test suite reports PASS
- 2.0 test network has been updated and nodes seem to be mining without issues.

**Pull request merged**
